apiVersion: v1
kind: Service
metadata:
  name: {{ include "tokenhub.fullname" . }}
  labels:
    {{- include "tokenhub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8080
      targetPort: api
      protocol: TCP
    - name: console
      port: 3000
      targetPort: console
      protocol: TCP
  selector:
    {{- include "tokenhub.selectorLabels" . | nindent 4 }}
